export const CONTENT = {
  es: {
    nav: {
      problema: "El reto",
      solucion: "Nuestra solución",
      productos: "Productos",
      planes: "Planes",
      fundador: "Fundador",
      contacto: "Contacto",
      cta: "Contáctanos",
    },
    hero: {
      tag: "Hidroponía en Cabo · Sin químicos · 100% orgánico",
      h1a: "Producto fresco, ",
      h1em: "cosechado hoy.",
      h1b: "",
      sub: "Canasta orgánica semanal entregada directo a tu casa en Cabo. Cultivada en nuestras torres hidropónicas. **De la granja a tu cocina en menos de 24 horas.**",
      ctaPrimary: "Escríbenos por WhatsApp",
      ctaSecondary: "Conoce el cultivo",
      fine: "Entregas a restaurantes y hoteles · BCS · Sin contratos",
      photoCaption: "Brócoli orgánico recién cosechado de torre hidropónica",
    },
    trust: [
      { num: "100%", label: "Orgánico, sin pesticidas" },
      { num: "−95%", label: "Agua vs. cultivo en suelo" },
      { num: "<24h", label: "De cosecha a tu cocina" },
      { num: "8+", label: "Productos cultivados localmente" },
    ],
    problem: {
      eyebrow: "El reto",
      title: "Cabo es desierto. El suelo no estaba hecho para la agricultura.",
      sub: "Por eso la mayoría del producto que llega a los restaurantes viaja días desde el centro de México — o más lejos. Llega cansado, mediano, y sin sabor.",
      points: [
        {
          h: "Suelo árido y salino",
          p: "La tierra de Baja California Sur tiene poca materia orgánica y demasiada sal del aire marino. Las hortalizas sufren.",
        },
        {
          h: "Agua, el recurso más escaso",
          p: "Cabo recibe menos de 250 mm de lluvia al año. Regar campo abierto desperdicia hasta el 70% del agua.",
        },
        {
          h: "Logística larga",
          p: "El producto convencional viaja 3 a 5 días desde tierra firme. Pierde frescura, color y nutrientes antes de llegar a tu plato.",
        },
      ],
    },
    solution: {
      eyebrow: "Nuestra solución",
      title: "Torres hidropónicas, aquí en Cabo.",
      sub: "Cultivamos en vertical, con agua nutrida y luz natural del desierto. Ni un solo químico. Ni un solo viaje largo.",
      features: [
        {
          h: "Cultivo vertical, sin tierra",
          p: "Las raíces crecen al aire en una cámara húmeda con nutrientes orgánicos. Sin tierra significa sin plagas del suelo, sin malezas, y sin pesticidas.",
        },
        {
          h: "95% menos agua",
          p: "El agua circula en circuito cerrado. Lo que la planta no absorbe vuelve al tanque. Aprovechamos cada gota — esencial en un desierto.",
        },
        {
          h: "Crecimiento 2–3× más rápido",
          p: "Las plantas reciben exactamente los nutrientes que necesitan, cuando los necesitan. Una lechuga lista en 28 días, no en 60.",
        },
        {
          h: "Sabor y tamaño superiores",
          p: "Sin estrés hídrico, sin compactación de raíz. Hojas más grandes, tomates más dulces, hierbas más aromáticas.",
        },
      ],
    },
    products: {
      eyebrow: "Lo que cultivamos",
      title: "Producto fresco para tu cocina, todo el año.",
      sub: "Cosechamos por la mañana y entregamos el mismo día. Pide por unidad o por kilo. Volumen para restaurantes y hoteles.",
      items: [
        { name: "Lechuga", note: "Hojas crujientes, baby leaf, romana, mantequilla" },
        { name: "Tomate", note: "Cherry, uva, bola, en racimo" },
        { name: "Cebolla", note: "Cambray, morada, blanca tierna" },
        { name: "Habanero", note: "Picor brillante, color intenso" },
        { name: "Pepino", note: "Persa, libanés, sin amargor" },
        { name: "Pimiento", note: "Rojo, amarillo, naranja" },
        { name: "Cilantro", note: "Aroma intenso, hojas firmes" },
        { name: "Rábano", note: "Picante, color vivo, fresco" },
      ],
      footer: "¿Buscas algo que no está en la lista? Cultivamos a pedido para clientes recurrentes.",
    },
    how: {
      eyebrow: "Cómo cultivamos",
      title: "De la semilla a tu cocina en pocas semanas.",
      sub: "Tres etapas, todas dentro de nuestra granja en Cabo. Ningún intermediario, ningún viaje largo.",
      steps: [
        { n: "1", h: "Semilla en sustrato limpio", p: "Germinamos las semillas en lana mineral con agua nutrida. Sin tierra, sin contaminación cruzada." },
        { n: "2", h: "Transplante a la torre", p: "Cuando la plántula tiene raíz, pasa a la torre vertical. Recibe sol directo y nutrientes en circuito cerrado." },
        { n: "3", h: "Cosecha y entrega", p: "Cosechamos la mañana de tu pedido. Llega a tu cocina antes del servicio, con raíz viva si lo prefieres." },
      ],
    },
    customers: {
      eyebrow: "Para quién es",
      title: "Pensado para familias que no se conforman.",
      sub: "Si te mudaste a Cabo desde una ciudad con Whole Foods o Erewhon, ya conoces la diferencia. Te la traemos a tu puerta cada semana.",
      forCardEyebrow: "Nuestro cliente principal",
      forCardTitle: "Familias en Cabo que viven a otro nivel.",
      forCardP: "Familias acostumbradas a lo mejor: producto orgánico, fresco, sin pesticidas, con sabor real. En Cabo no hay un Whole Foods. Lo que sí hay somos nosotros — cultivando aquí mismo y entregando a tu cocina en menos de 24 horas.",
      problems: [
        { h: "Sin opciones premium en Cabo", p: "Los supermercados locales rara vez tienen producto verdaderamente orgánico, y lo que llega ya viajó días desde tierra firme." },
        { h: "Cero información sobre el origen", p: "En la tienda no sabes quién lo cultivó, con qué agua o qué químicos. Aquí lo sabes todo: cultivado en hidroponía, sin pesticidas, en Los Cabos." },
        { h: "Producto cansado tras días en camión", p: "La diferencia entre lechuga cortada esta mañana y lechuga de hace una semana se nota en cada bocado — y en la nutrición que entrega a tu familia." },
        { h: "Tiempo perdido buscando lo bueno", p: "Visitar 3 tiendas el sábado para encontrar tomate decente no es plan. Recibe lo mejor en casa, sin pensarlo." },
      ],
      alsoServe: "También servimos a restaurantes y hoteles de alto nivel. Pide por volumen — escríbenos.",
    },
    plans: {
      eyebrow: "Planes",
      title: "Tu canasta orgánica, cada semana.",
      sub: "Una entrega semanal con lo mejor que cosechamos. Pausa o cancela cuando quieras. Sin contratos.",
      includes: "Cada canasta incluye:",
      includesItems: [
        "2 lechugas frescas (variedad de la semana)",
        "Tomates en racimo + cherry",
        "Pepino persa y rábanos",
        "Hierbas: cilantro y/o albahaca",
        "Cebolla cambray y pimientos",
        "1 sorpresa de cosecha (habanero, kale, etc.)",
      ],
      cards: [
        {
          name: "Suscripción semanal",
          tag: "Lo que recomendamos",
          price: "$100",
          unit: "USD / semana",
          badge: "75% off primera semana",
          firstWeek: "Tu primera canasta: $25 USD",
          featured: true,
          cta: "Empezar suscripción",
          features: ["Entrega semanal en tu casa", "Pausa o cancela cuando quieras", "Lista personalizable cada semana", "Precio fijo, sin sorpresas", "Prioridad en cosechas especiales"],
          fine: "Sin contratos. Pausa cuando viajas.",
        },
        {
          name: "Canasta única",
          tag: "Pruébala una vez",
          price: "$150",
          unit: "USD / una entrega",
          badge: null,
          firstWeek: null,
          featured: false,
          cta: "Comprar una canasta",
          features: ["Una entrega, sin compromiso", "Mismo producto, misma calidad", "Ideal para probar antes de suscribirte", "Entrega en 48 horas"],
          fine: "Sin renovación automática.",
        },
      ],
    },
    founder: {
      eyebrow: "Sobre el fundador",
      title: "Alex Rodríguez · Ingeniero Agrónomo",
      p1: "Alex creció en el centro de Colombia, una de las regiones con mayor biodiversidad del mundo. Estudió en la Universidad del Tolima, donde se convirtió en Ingeniero Agrónomo.",
      p2: "Durante los siguientes 20 años viajó por Colombia construyendo invernaderos para cultivar de todo: desde flores y tomates hasta frutas exóticas. Aprendió a construir invernaderos industriales que hoy abastecen de alimentos a millones de personas en el mundo.",
      p3: "Después de visitar a su hermana en Cabo, se dio cuenta de que existe una gran necesidad de productos frescos y orgánicos para los restaurantes y hoteles de alto nivel que siguen creciendo en la zona.",
      p4: "Su objetivo es ayudar a los negocios de Cabo a ofrecer ingredientes saludables, para que la gente se mantenga sana y los negocios locales prosperen.",
      stats: [
        { num: "20+", label: "Años de experiencia" },
        { num: "1", label: "Universidad del Tolima" },
        { num: "∞", label: "Pasión por el cultivo" },
      ],
    },
    cta: {
      h: "¿Listo para servir el mejor producto de Cabo?",
      sub: "Suscríbete a tu canasta semanal o pide una entrega única. Empezamos esta semana.",
      btnWhatsapp: "Escríbenos por WhatsApp",
      btnEmail: "Ver planes",
      fine: "Respuesta en menos de 24 horas · Entrega martes a sábado",
    },
    contact: {
      eyebrow: "Contacto",
      title: "Hablemos de tu próximo pedido.",
      sub: "Compártenos los datos de tu restaurante u hotel. Nuestro equipo te contacta personalmente con muestras y precios.",
      fields: {
        name: "Tu nombre",
        business: "Restaurante u hotel",
        whatsapp: "WhatsApp",
        email: "Correo (opcional)",
        items: "¿Qué producto te interesa?",
        notes: "Notas (volumen estimado, días de servicio, etc.)",
      },
      submit: "Enviar pedido",
      submitting: "Enviando…",
      success: "¡Gracias! Te contactamos en menos de 24 horas.",
      privacy: "Tus datos sólo se usan para responder tu pedido. Nunca compartimos información.",
    },
    footer: {
      tag: "Producto orgánico cultivado en hidroponía. San José del Cabo, BCS, México.",
      colA: "Producto",
      colB: "Empresa",
      colC: "Contacto",
      links: {
        a: ["Lechugas", "Tomates", "Hierbas frescas", "Chiles y picantes"],
        b: ["Sobre Alex", "Nuestra granja", "Cómo cultivamos", "Sustentabilidad"],
        c: ["WhatsApp", "Email", "Visítanos", "Instagram"],
      },
      copy: "© 2026 Simply Fresh Cabo · Hecho con sol del desierto.",
    },
  },
  en: {
    nav: {
      problema: "The challenge",
      solucion: "Our solution",
      productos: "Products",
      fundador: "Founder",
      contacto: "Contact",
      cta: "Buy Now",
      planes: "Plans",
    },
    hero: {
      tag: "Hydroponics in Cabo · No chemicals · 100% organic",
      h1a: "Fresh produce, ",
      h1em: "harvested today.",
      h1b: "",
      sub: "Weekly organic basket delivered to your home in Cabo. Grown in our hydroponic towers. **From farm to your kitchen in under 24 hours.**",
      ctaPrimary: "Buy Now",
      ctaSecondary: "See the farm",
      fine: "Delivering to Cabo restaurants & hotels · BCS · No contracts",
      photoCaption: "Organic broccoli, fresh-cut from a hydroponic tower",
    },
    trust: [
      { num: "100%", label: "Organic, pesticide-free" },
      { num: "−95%", label: "Less water than soil farming" },
      { num: "<24h", label: "Harvest to your kitchen" },
      { num: "8+", label: "Crops grown locally" },
    ],
    problem: {
      eyebrow: "The challenge",
      title: "Cabo is a desert. The soil was never built for farming.",
      sub: "That's why most produce in restaurants travels for days from central Mexico — or further. It arrives tired, average, and lacking flavor.",
      points: [
        { h: "Dry, salty soil", p: "Baja California Sur soil has very little organic matter and too much salt from the sea air. Vegetables struggle here." },
        { h: "Water, the scarcest resource", p: "Cabo gets under 250 mm of rain a year. Open-field irrigation wastes up to 70% of every drop." },
        { h: "Long logistics", p: "Conventional produce travels 3–5 days from the mainland. It loses freshness, color and nutrients before it reaches your plate." },
      ],
    },
    solution: {
      eyebrow: "Our solution",
      title: "Hydroponic towers, right here in Cabo.",
      sub: "We grow vertical, in nutrient-rich water under the desert sun. Not a single chemical. Not a single long trip.",
      features: [
        { h: "Vertical, soilless growing", p: "Roots grow into a humid chamber fed with organic nutrients. No soil means no soil-borne pests, no weeds, and no pesticides." },
        { h: "95% less water", p: "Water recirculates in a closed loop. Whatever the plant doesn't absorb returns to the tank. Every drop counts — essential in a desert." },
        { h: "2–3× faster growth", p: "Plants get exactly the nutrients they need, when they need them. A head of lettuce in 28 days, not 60." },
        { h: "Better flavor and size", p: "No water stress, no root compaction. Bigger leaves, sweeter tomatoes, more aromatic herbs." },
      ],
    },
    products: {
      eyebrow: "What we grow",
      title: "Fresh produce for your kitchen, year-round.",
      sub: "Harvested in the morning, delivered the same day. Order by unit or by kilo. Volume pricing for restaurants and hotels.",
      items: [
        { name: "Lettuce", note: "Crispy leaf, baby leaf, romaine, butter" },
        { name: "Tomato", note: "Cherry, grape, slicer, on the vine" },
        { name: "Onion", note: "Cambray, red, tender white" },
        { name: "Habanero", note: "Bright heat, deep color" },
        { name: "Cucumber", note: "Persian, Lebanese, no bitterness" },
        { name: "Bell pepper", note: "Red, yellow, orange" },
        { name: "Cilantro", note: "Intense aroma, firm leaves" },
        { name: "Radish", note: "Sharp bite, vivid color" },
      ],
      footer: "Need something not on the list? We grow on-demand for recurring clients.",
    },
    how: {
      eyebrow: "How we grow",
      title: "From seed to your kitchen in a few weeks.",
      sub: "Three stages, all inside our farm in Cabo. No middlemen, no long trips.",
      steps: [
        { n: "1", h: "Seed in clean substrate", p: "Seeds germinate in mineral wool fed with nutrient water. No soil, no cross-contamination." },
        { n: "2", h: "Transplant to the tower", p: "Once rooted, the seedling moves to the vertical tower. It gets direct sun and closed-loop nutrients." },
        { n: "3", h: "Harvest and delivery", p: "We cut the morning of your order. It reaches your kitchen before service — with living root if you prefer." },
      ],
    },
    customers: {
      eyebrow: "Who it's for",
      title: "Built for families who don't settle.",
      sub: "If you moved to Cabo from a city with Whole Foods or Erewhon, you know the difference. We bring it to your door every week.",
      forCardEyebrow: "Our main customer",
      forCardTitle: "Families in Cabo who live at the top tier.",
      forCardP: "Families used to the best: organic, fresh, pesticide-free produce with real flavor. Cabo doesn't have a Whole Foods. What it does have is us — growing right here and delivering to your kitchen in under 24 hours.",
      problems: [
        { h: "No premium options in Cabo", p: "Local supermarkets rarely carry truly organic produce, and what arrives has already traveled days from the mainland." },
        { h: "Zero info about the source", p: "At the store you don't know who grew it, with what water, with what chemicals. Here you know everything: hydroponically grown, pesticide-free, in Los Cabos." },
        { h: "Tired produce after days in transit", p: "The difference between lettuce cut this morning and lettuce cut a week ago shows up in every bite — and in the nutrition your family gets." },
        { h: "Time lost hunting for the good stuff", p: "Driving to 3 stores on Saturday to find a decent tomato isn't a plan. Get the best, at home, without thinking." },
      ],
      alsoServe: "We also serve high-end restaurants and hotels. Order by volume — get in touch.",
    },
    plans: {
      eyebrow: "Plans",
      title: "Your organic basket, every week.",
      sub: "One weekly delivery with the best we harvest. Pause or cancel anytime. No contracts.",
      includes: "Every basket includes:",
      includesItems: [
        "2 fresh lettuces (variety of the week)",
        "Tomatoes on the vine + cherry",
        "Persian cucumber and radishes",
        "Herbs: cilantro and/or basil",
        "Spring onion and bell peppers",
        "1 harvest surprise (habanero, kale, etc.)",
      ],
      cards: [
        {
          name: "Weekly subscription",
          tag: "What we recommend",
          price: "$100",
          unit: "USD / week",
          badge: "75% off your first week",
          firstWeek: "Your first basket: $25 USD",
          featured: true,
          cta: "Buy Now",
          features: ["Weekly delivery to your home", "Pause or cancel anytime", "Customizable list each week", "Fixed price, no surprises", "Priority on special harvests"],
          fine: "No contracts. Pause when you travel.",
        },
        {
          name: "Single basket",
          tag: "Try it once",
          price: "$150",
          unit: "USD / one delivery",
          badge: null,
          firstWeek: null,
          featured: false,
          cta: "Buy one basket",
          features: ["One delivery, no commitment", "Same produce, same quality", "Great for trying before subscribing", "Delivered in 48 hours"],
          fine: "No auto-renewal.",
        },
      ],
    },
    founder: {
      eyebrow: "About the founder",
      title: "Alex Rodríguez · Agricultural Engineer",
      p1: "Alex grew up in central Colombia, one of the most biodiverse regions in the world. He studied at the Universidad del Tolima, where he became an Agricultural Engineer.",
      p2: "Over the next 20 years he traveled across Colombia building greenhouses to grow everything from flowers to tomatoes to exotic fruits. He learned how to build industrial greenhouses that today supply millions of people around the world.",
      p3: "After visiting his sister in Cabo, he saw a huge need for fresh organic produce to serve the upscale restaurants and hotels growing in the area.",
      p4: "His goal is to help Cabo businesses serve healthier ingredients, so people stay fit and local businesses thrive.",
      stats: [
        { num: "20+", label: "Years of experience" },
        { num: "1", label: "Universidad del Tolima" },
        { num: "∞", label: "Passion for growing" },
      ],
    },
    cta: {
      h: "Ready to taste the best produce in Cabo?",
      sub: "Order your organic basket today. We harvest fresh and deliver to your door.",
      btnWhatsapp: "Message us on WhatsApp",
      btnEmail: "Buy Now",
      fine: "Reply in under 24 hours · Delivery Tuesday to Saturday",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's talk about your next order.",
      sub: "Share your restaurant or hotel info. Our team contacts you personally with samples and pricing.",
      fields: {
        name: "Your name",
        business: "Restaurant or hotel",
        whatsapp: "WhatsApp",
        email: "Email (optional)",
        items: "Which produce interests you?",
        notes: "Notes (estimated volume, service days, etc.)",
      },
      submit: "Send request",
      submitting: "Sending…",
      success: "Thank you! We'll be in touch within 24 hours.",
      privacy: "Your info is only used to respond to your request. We never share it.",
    },
    footer: {
      tag: "Organic produce, hydroponically grown. San José del Cabo, BCS, Mexico.",
      colA: "Produce",
      colB: "Company",
      colC: "Contact",
      links: {
        a: ["Lettuce", "Tomatoes", "Fresh herbs", "Chiles & heat"],
        b: ["About Alex", "Our farm", "How we grow", "Sustainability"],
        c: ["WhatsApp", "Email", "Visit us", "Instagram"],
      },
      copy: "© 2026 Simply Fresh Cabo · Made with desert sun.",
    },
  },
};

export type Lang = "es" | "en";
export type Copy = (typeof CONTENT)["es"];
